name: Tests

on:
    pull_request:
        branches:
        - master
    push:
        branches:
        - master

jobs:
  build:
    name: CI
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        resolver: [nightly, lts-21, lts-20, lts-19]
        # # Bugs in GHC make it crash too often to be worth running
        # exclude:
        #   - os: macos-latest
        #     resolver: lts-9
        #   - os: windows-latest
        #     resolver: lts-15
        #   - os: windows-latest
        #     resolver: nightly

    steps:
      - name: Clone project
        uses: actions/checkout@v4

      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: ~/.stack
          key: ${{ runner.os }}-${{ matrix.resolver }}-${{ hashFiles('stack.yaml') }}
          restore-keys: |
            ${{ runner.os }}-${{ matrix.resolver }}-

      - name: Build and run tests
        shell: bash
        run: stack test --bench --no-run-benchmarks --haddock --no-haddock-deps --no-terminal --resolver=${{ matrix.resolver }}
        # run: |
        #     set -ex
        #     stack upgrade || curl -sSL https://get.haskellstack.org/ | sh -s - -f
        #     stack test --bench --no-run-benchmarks --haddock --no-haddock-deps --no-terminal --resolver=${{ matrix.resolver }}
